### ISSUE TITLE
ESLify Everything stops after reading .jsons

### ISSUE THREAD

**Issue by MoonbeamLure** [Michael-wigontherun/ESLifyEverything#10]
Hi. Im not sure what Im doing wrong, but I downloaded 4.3 or whatever's the most recent version and it always stops... when I enabled dev logging, it gives this: 

<img width="272" alt="image" src="https://user-images.githubusercontent.com/106170274/208341801-8b82e59b-bfe9-49f8-98b2-6914af9c8c22.png">

Then when I press enter it just closes. I've tried just about every settings combnination and it doesn't seem like it ever gets past this menu. It works as intended when I use 4.2.0.

**Comment by MoonbeamLure** [comment]
Yeah, I dunno what happened between yesterday and today but it seems to work now? I'll have to open a new issue or something if it persists.

**Comment by Michael-wigontherun** [comment]
You probably have scripts in the output folder. I enabled the log reader and the zMerge cacher to build the data even without needing to clear stuff.

**Comment by MoonbeamLure** [comment]
That's weird, it didn't ever bring up the ESLify Output script window, but that makes sense. I'll keep an eye out. Thank you! And, the program is working like a charm now. Excellent work! You should be proud of yourself.

Sent from Outlook<http://aka.ms/weboutlook>
________________________________
