### ISSUE TITLE
If anything is logged below Please also report the scripts names and mods that they originated from with a sceenshot of the error from the Script ESLify section to the Bugs section on Nexus or create a new issue on GitHub.

### ISSUE THREAD

**Issue by Charolas** [Michael-wigontherun/ESLifyEverything#12]
NIOPoseAdjustments.psc from https://www.loverslab.com/files/file/6670-nioverride-pose-adjustments-objects-se/

[ESLifyEverything_Log.txt](https://github.com/Michael-wigontherun/ESLifyEverything/files/10460399/ESLifyEverything_Log.txt)

**Comment by Michael-wigontherun** [comment]
I believe it had to do with the same thing as in #14 and https://github.com/Orvid/Champollion/issues/13
