### ISSUE TITLE
Error compacting voice files on  v4.4.1

### ISSUE THREAD

**Issue by Tako-kun01** [Michael-wigontherun/ESLifyEverything#13]
Hi Michael plz halp..

AggregateException. Please report to GitHub with log file.
System.AggregateException: One or more errors occurred. (Could not find a part of the path 'D:\Games\Steam\steamapps\common\Skyrim Special Edition\Mod Organizer 2\mods\ESLify Everything\sound\voice\ImGladYoureHere.esp\FemaleUniqueAstrid\WW42HugFol_WW42HugFollower_00000803_1.fuz'.)
 ---> System.IO.DirectoryNotFoundException: Could not find a part of the path 'D:\Games\Steam\steamapps\common\Skyrim Special Edition\Mod Organizer 2\mods\ESLify Everything\sound\voice\ImGladYoureHere.esp\FemaleUniqueAstrid\WW42HugFol_WW42HugFollower_00000803_1.fuz'.
   at System.IO.FileSystem.CopyFile(String sourceFullPath, String destFullPath, Boolean overwrite)
   at ESLifyEverything.Program.VoiceESLifyModData(CompactedModData modData, String dataStartPath) in C:\Modding\SkyrimSE\ESLifyEverything\ESLifyEverything\ProgramSteps.cs:line 736
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at ESLifyEverything.Program.VoiceESLifyMod(CompactedModDa
[ESLifyEverything_Log.txt](https://github.com/Michael-wigontherun/ESLifyEverything/files/10470887/ESLifyEverything_Log.txt)
ta modData) in C:\Modding\SkyrimSE\ESLifyEverything\ESLifyEverything\ProgramSteps.cs:line 665
   at ESLifyEverything.Program.VoiceESLifyEverything() in C:\Modding\SkyrimSE\ESLifyEverything\ESLifyEverything\ProgramSteps.cs:line 624
   at ESLifyEverything.Program.VoiceESlIfyMenu() in C:\Modding\SkyrimSE\ESLifyEverything\ESLifyEverything\ProgramSteps.cs:line 607
   at ESLifyEverything.Program.Main(String[] args) in C:\Modding\SkyrimSE\ESLifyEverything\ESLifyEverything\Program.cs:line 139
One or more errors occurred. (Could not find a part of the path 'D:\Games\Steam\steamapps\common\Skyrim Special Edition\Mod Organizer 2\mods\ESLify Everything\sound\voice\ImGladYoureHere.esp\FemaleUniqueAstrid\WW42HugFol_WW42HugFollower_00000803_1.fuz'.)
Press Enter to exit...

**Comment by Michael-wigontherun** [comment]
You unlocked mo2 while ESLify Everything was running. MO2 has a "hick up" when you unlock it and it closes it's VSU for a split second before, then enabling it in the background of the process is still running.

**Comment by Tako-kun01** [comment]
That doesn't seem to be it.. I ran it again and it errored in the same
place, and the MO2 lock is still in place.  I do think I had MO2 unlocked
when I was compacting the formIDs and ESLing the plugins in SSEdit, but
that wouldn't affect Eslify Everything, would it?

**Comment by Michael-wigontherun** [comment]
I deleted that comment after I looked at actual path. It's the output path that wasn't found I have to look at it later.

**Comment by Michael-wigontherun** [comment]
Where currently does this path end for you `D:\Games\Steam\steamapps\common\Skyrim Special Edition\Mod Organizer 2\mods\ESLify Everything\sound\voice\ImGladYoureHere.esp\FemaleUniqueAstrid`?

**Comment by Tako-kun01** [comment]
My actual file path is the same as what you see in the log:

*D:\Games\Steam\steamapps\common\Skyrim Special Edition\Mod Organizer
2\mods\ESLify Everything\sound\voice\ImGladYoureHere.esp\FemaleUniqueAstrid*

There are no files in the folder, although it was able to create the
DLC2SeranaVoice folder shown below, and there is a .fuz file in it.

D:\Games\Steam\steamapps\common\Skyrim Special Edition\Mod Organizer
2\mods\ESLify Everything\sound\voice\ImGladYoureHere.esp\DLC1SeranaVoice

**Comment by Michael-wigontherun** [comment]
So I tried eslifing "Glad Your Here" and I didn't get the crash.

1) What version of "Glad Your Here" do you have? 3.2.3 worked fine.

2) Try deleting the folder `ImGladYoureHere.esp` in `D:\Games\Steam\steamapps\common\Skyrim Special Edition\Mod Organizer 2\mods\ESLify Everything\sound\voice\` and re running ESLify Everything.

3) Is your computer flagging it as a virus and locking it from copping files?

4) Try opening `D:\Games\Steam\steamapps\common\Skyrim Special Edition\Data\sound\voice\ImGladYoureHere.esp\FemaleUniqueAstrid\WW42HugFol_WW42HugFollower_0000D8D0_1.fuz` with VLC or another program capable of opening and playing the voice file. If it can't play or it says its unable to read try deleting the file altogether and try running ESLify Everything.

**Comment by Tako-kun01** [comment]
1. I'm also using v3.2.3
2. I deleted the folder and re-ran  eslify everything.  It recreated the folder and errored in the same place.
3. I have an exception in Defender for the eslify everything process and for the MO2 mod folder.  I checked the folder permissions for the MO2/mods subfolders to make sure all users had full access.
4. I tried playing the voice file and was able to do so.  I also re-downloaded and re-installed the files (other than the compacted esp) just in case there was some kind of file corruption.  Issue still remained though.

I tried deleting the \FemaleUniqueAstrid\WW42HugFol_WW42HugFollower_0000D8D0_1.fuz file from the mod and then running eslify everything.  It then errored on:

System.IO.DirectoryNotFoundException: Could not find a part of the path 'D:\Games\Steam\steamapps\common\Skyrim Special Edition\Mod Organizer 2\mods\ESLify Everything\sound\voice\ImGladYoureHere.esp\FemaleUniqueDelphine\WW42HugFol_WW42HugFollower_00000805_1.fuz'."

I then deleted the \FemaleUniqueDelphine\WW42HugFol_WW42HugFollower_0000D8D2_1.fuz as well and re-ran eslify and it errored on:

---> System.IO.DirectoryNotFoundException: Could not find a part of the path 'D:\Games\Steam\steamapps\common\Skyrim Special Edition\Mod Organizer 2\mods\ESLify Everything\sound\voice\ImGladYoureHere.esp\FemaleCondescending\WW42HugFol_WW42HugFollower_00000809_1.fuz'.

**Comment by Tako-kun01** [comment]
[ImGladYoureHere.esp.zip](https://github.com/Michael-wigontherun/ESLifyEverything/files/10476704/ImGladYoureHere.esp.zip)

This is the contents of the ESLify Everything\sound\voice\ImGladYoureHere.esp\ folder.  It was able to successfully copy several .fuz files before it reaches the point where it starts erroring.

**Comment by Tako-kun01** [comment]
Could it possibly be file name length related?  I have long file paths enabled in windows, but does Eslify Everything handle file paths longer than 256 characters?

**Comment by Michael-wigontherun** [comment]
Try using this version: https://github.com/Michael-wigontherun/ESLifyEverything/releases/tag/P4.4.2

I changed the copy to read bytes and save bytes

**Comment by Tako-kun01** [comment]
Success!  Thank you!  And congratulations, this tool is such a game-changer..  I just compacted ~75 mods that themselves touched a further ~500 mods.. so much work saved.

I am still getting the issue with Champolion hanging occasionally while decompiling/recompiling described here:

https://forums.nexusmods.com/index.php?/topic/12008548-eslify-everything-espfe-everything/?p=119735473

I'll try to document exactly what's happening in case it's helpful for you..
