### ISSUE TITLE
Compiling scripts hangs indefinitely

### ISSUE THREAD

**Issue by googlepox** [Michael-wigontherun/ESLifyEverything#14]
Hello!

I just downloaded the latest version from the Github and compacted some mods and ran the program. I left it running for several hours but when it got to this point 

```
If anything is logged below
Please also report the scripts names and mods that they originated from with a sceenshot of the error from
the Script ESLify section to the Bugs section on Nexus or create a new issue on GitHub.
I need this data to try to better find out what Script ESLify needs to check for before attempting to compile scripts.
Important <
"C:\Users\brand\Desktop\Tools\SSEEdit\ESLifyEverything\ChangedScripts" -q -f="TESV_Papyrus_Flags.flg" -a -i="C:\Users\brand\Desktop\Tools\SSEEdit\ESLifyEverything\ExtractedBSAModData\Source\Scripts" -o="E:\SteamLibrary\steamapps\common\Skyrim Special Edition\Mod Organizer\mods\OutputFolder\Scripts"
```

It stopped doing anything. No errors from what I can see. The scripts are from [Improved Adoptions](https://www.nexusmods.com/skyrimspecialedition/mods/4713), if that helps.

[Here's the full log as well.](https://www.dropbox.com/s/jh7hyh3lbuideyo/ESLifyEverything_Log.txt?dl=0)

**Comment by Michael-wigontherun** [comment]
It's with the compiler. When it happens just use task manager to close papyrus compiler. ESLify Everything will switch to one by one.

The papyrus compiler is a really crappy program but it's all we get.
