### ISSUE TITLE
JSLOT files

### ISSUE THREAD

**Issue by TheMerricat** [Michael-wigontherun/ESLifyEverything#17]
In the documentation you indicate you would like to be pinged either by an opened issue or comment on the Nexus page if we have data that could/should be added to the program as candidates to be rewritten when a file is ESLified.

JSLOT files are pure text files that Racemenu creates when you ask it to save a preset and are commonly exchanged for folk who want to share character appearances and are setup with direct references in the standard filename|formID format.

An example snippet from one that came in a mod list:

>  "headParts" : [
>       {
>          "formId" : 333071,
>          "formIdentifier" : "Skyrim.esm|05150F",
>          "type" : 0
>       },
>       {
>          "formId" : 100665862,
>          "formIdentifier" : "High Poly Head.esm|000A06",
>          "type" : 1
>       },
>       {
>          "formId" : 967090,
>          "formIdentifier" : "Skyrim.esm|0EC1B2",
>          "type" : 2
>       },
>       {
>          "formId" : 520614728,
>          "formIdentifier" : "KS Hairdo's.esp|07F348",
>          "type" : 3
>       },
>       {
>          "formId" : 721465404,
>          "formIdentifier" : "TheEyesOfBeauty.esp|00B03C",
>          "type" : 6
>       },
>       {
>          "formId" : 452986881,
>          "formIdentifier" : "Koralina's Eyebrows.esp|000801",
>          "type" : 7
>       }
>    ],
>    "modNames" : [
>       "High Poly Head.esm",
>       "KS Hairdo's.esp",
>       "Koralina's Eyebrows.esp",
>       "Skyrim.esm",
>       "TheEyesOfBeauty.esp"
>    ],
>    "mods" : [
>       {
>          "index" : 0,
>          "name" : "Skyrim.esm"
>       },
>       {
>          "index" : 6,
>          "name" : "High Poly Head.esm"
>       },
>       {
>          "index" : 27,
>          "name" : "Koralina's Eyebrows.esp"
>       },
>       {
>          "index" : 31,
>          "name" : "KS Hairdo's.esp"
>       },
>       {
>          "index" : 43,
>          "name" : "TheEyesOfBeauty.esp"
>       }
>    ]

**Comment by Michael-wigontherun** [comment]
Yes I would like people to do that. But racemenu has already been supported for a while now.
