### ISSUE TITLE
I'm not sure if this is an issue to report or not.... from the log of running

### ISSUE THREAD

**Issue by Grosaprap** [Michael-wigontherun/ESLifyEverything#18]
[Screenshot of execution of app requesting a report?](https://i.imgur.com/QcycR21.png
)
I have the full log in a gist and can share it if requested, as well as some information about what is installed. 

But if the issue is actually not an issue, then I guess my issue would be that the request in app to share this info might need to be reworded slightly to prevent false positives like this?

**Comment by Michael-wigontherun** [comment]
Its fine
