### ISSUE TITLE
Minor Issue

### ISSUE THREAD

**Issue by Grosaprap** [Michael-wigontherun/ESLifyEverything#19]
This isn't a breaking bug, if the program detects that the output folder has previously updated script files in it, it instructs you to remove those files and opens the explorer window for you.

I understand why that is necessary, however... if after running through the latest changes the program determines nothing needs to be done, it simply tells you to hit enter to exit the program, it doesn't regenerate those scripts that were just deleted. As a result if someone isn't watching closely, they could miss realizing that they need to 'undelete' those scripts and replace them back into the folder.

**Comment by Michael-wigontherun** [comment]
It doesn't because deleting then from the output folder doesn't update the one in the data file to the original ones. You don't need to delete them at that point because it's not going to roll Script ESLify. It's meant to allow you to do other minor things if you need to.
