### ISSUE TITLE
Is it stuck? // this tools deserves a video.

### ISSUE THREAD

**Issue by TeusDev** [Michael-wigontherun/ESLifyEverything#20]
"Running Champollion for BSA scripts.
Champollion: 56789 files processed in 15.091 s
BSA scripts Champollion Ended.
Running Champollion on loose scripts."

does it take this much for large modlists? i leaved it for almost 2 hours on that champollion phase and nothing.

i think it would be nice to have a video of how to install and use it on MO2.. i feel that this is being nich for ppl that knows a lot of modding and keep most of the community out of luck to setup, the directions are very complicated to be followed imho.

**Comment by Michael-wigontherun** [comment]
Except it is only unpacking one archive and changing 2 settings. The rest is either included or something that is an easy stream download.

If it starts to sit trying to decompile files use Task Manager to end the champolion.exe possess not eslifyeverthing.exe and press enter inside the ESLify everything's console window
