### ISSUE TITLE
Compile Error

### ISSUE THREAD

**Issue by CineManiac93** [Michael-wigontherun/ESLifyEverything#3]
Hey, I was instructed to post this on here. The script is from Immersive Interactions as you can see below. 

![ESLify Compile Error](https://user-images.githubusercontent.com/49701521/197370929-afc76ce9-fe80-4622-af42-9578ce17dcba.jpg)

![Immersive Interactions](https://user-images.githubusercontent.com/49701521/197370971-1c044c50-ede0-4d6c-a0cf-0106c149c09f.png)

**Comment by Michael-wigontherun** [comment]
I need you to send me the source script and your log with the error sent as text through something like [https://pastebin.com](https://pastebin.com).

**Comment by Michael-wigontherun** [comment]
Yey, I need your script. Mine compiled perfectly fine. With skse and skyUI. If you don't have either one of those the MCM script is unimportant and wont do anything in skyrim. It is an MCM for SkyUI.

**Comment by CineManiac93** [comment]
Apologies, I deactivated the mod and ran the program again so the log was overwritten. I didn't save it, unfortunately. 

I'm not sure if you wanted the script in a pastebin as well.

https://pastebin.com/2cdx1xrF

**Comment by Michael-wigontherun** [comment]
Its been quarantined which version of Immersive interactions are you using.

**Comment by CineManiac93** [comment]
1.67

**Comment by Michael-wigontherun** [comment]
Ensure that you fix any CompactedModData files outputted by ESLify Everything, there was an error with the import. See the top sticky post on the ESLify Everything's Nexus Page. And try again.
If that doesn't fix the issue, are you using 3.3.0? And what SKSE and SkyUI version are you using? It compiled fine on SE's SKSE and SkyUI.

**Comment by MoonbeamLure** [comment]
I have the mod downloaded so I decided to give it a shot. I got the same error but on a different script (_camp_InstinctsEffects.psc).  here's what happened:

The original script has a call to GetFormFromFile(0x0A0AA13), which translates to decimal as 167815699 in the decompiled script, which is the correct number. However, after the compilation failed in ESLifyEverything despite succeeding in PCA (using the non-changed script) I decided to look at the script in the ChangedScripts folder to see if anything was amiss. The number in the CallFormFromFile was 0xa00000813 (42949675027 in decimal), far too large to be an Int32 number. 

I also uninstalled and reinstalled all of the required scripts and nothing's different other than ESLifyEverything seems to only take the last 6 digits, ignoring whatever comes before them -- which, if a mod author such as the guy who wrote Immersive Interactions writes the load order slot of the FormID at the time of writing the script ESLify Everything's FormID swapper function seems to mess up. I have no idea why your ESLifyEverything would compile and ours wouldn't though.

I am currently checking to see if anything else could be causing it. Here's the image from below showing the changes to the FormIDs: 

<img width="666" alt="image" src="https://user-images.githubusercontent.com/106170274/197420550-1440be96-8e95-462f-80e5-f6cd0dcf5be1.png">

**Comment by Michael-wigontherun** [comment]
0xa00000813 does not matter it can be how ever large it will only keep the last 6 digits

**Comment by MoonbeamLure** [comment]
Huh, interesting. Well, I don't know then. Le me do some more investigating around the sources.

**Comment by MoonbeamLure** [comment]
I honestly can't find anything mucked up with our sources. I've doubly-verified everything. So I decided to run it again this time looking directly at how the FormID calls are changed in the scripts with an experiment to see if my hunch about the 0A part of the FormID is correct. 

The numbers come directly from the scripts. 

For comparison:

(Original Source Script) > (Original Script Decompiled) > ESLifyEverything > (ChangedScript Folder script) > (Decompiled Script from Output Folder)

0A00AA13 > 167,815,699 > a00000813 >  42,949,675,027

Compile failed: <path redacted for readability>\_Camp_InstinctsEffects.psc(0,0): error while attempting to read script _Camp_InstinctsEffects: Value was either too large or too small for an Int32. No output generated for _Camp_InstinctsEffects.psc, compilation failed.

Then I ran it again but this time using the base script instead of leaving the 0A at the start, I cut it off so that there were only 6 digits left as you talked about which led to this:

00AA13 > 4,353 > 000813 > 2,067
Compile succeeded

Interestingly, it compiles in PCA and gives me the number for the old script (0A00AA13 > 167,815,699), 

Line from ChangedScript: 
<img width="821" alt="image" src="https://user-images.githubusercontent.com/106170274/197424281-76eea7dc-db1a-4291-a47b-c428fd25838b.png">

Line from Output Script decompiled
<img width="803" alt="image" src="https://user-images.githubusercontent.com/106170274/197424308-b99975e7-f6e2-4293-8e3c-58c93391c6be.png">

however when I compiled it using a command line for the default Bethesda compiler, the same error occurred: 

<img width="858" alt="image" src="https://user-images.githubusercontent.com/106170274/197423809-19e7fbee-21b8-427c-a09e-bc038aee7e0c.png">

So I really think there's something going on here. I have no idea why it'd fail in one case but not the other. It's especially confusing that PCA is outputting the old FormID in Decimal form instead of the new one.

**Comment by Michael-wigontherun** [comment]
I'm going to try adding a check and remove for the extra hex and we will see. Its possible it is the issue. I don't know what though, mine compiles fine after eslifing Immersive Interactions.

Of course I am using the Papyrus compiler from Bethesda Launcher and not Steam. I haven't updated my game ever, nor let Steam try it.

**Comment by Michael-wigontherun** [comment]
Can one of you try it with this build and see if the actual issue is fixed and you can compile and decompile with the FormID intact.

[https://github.com/Michael-wigontherun/ESLifyEverything/releases/tag/V3.3.1](https://github.com/Michael-wigontherun/ESLifyEverything/releases/tag/V3.3.1)

**Comment by MoonbeamLure** [comment]
> I'm going to try adding a check and remove for the extra hex and we will see. Its possible it is the issue. I don't know what though, mine compiles fine after eslifing Immersive Interactions.
> 
> Of course I am using the Papyrus compiler from Bethesda Launcher and not Steam. I haven't updated my game ever, nor let Steam try it.

That might be it. I think the steam version of the CK is a newer version and that might have done something with the compiler. 

I am currently busy but I will give it a shot when I get home -- thanks!

**Comment by CineManiac93** [comment]
Hey, just ran the new build. Now getting compilation fail on Immersive Interactions "simplyknockmainscript.psc".

Command output https://pastebin.com/QQsniQ76

It's the same Immersive Interactions mod. I just reinstalled it.

If you need anything else please let me know.

I couldn't post the ESLifyEverything log on Pastebin as it exceed the 512 kb limit.

![WindowsTerminal_m1sL1VRhiK](https://user-images.githubusercontent.com/49701521/197600127-b661bd4e-8a74-4214-aaf1-a2d34bb3ba66.png)

**Comment by Michael-wigontherun** [comment]
Try running it again it doesn't give any kind of error its just no output generated.

I don't even know where to go from that.

**Comment by CineManiac93** [comment]
Did you see the last photo? It's the same error but also simplyknockmainscript.

Will be running it again.

**Comment by Michael-wigontherun** [comment]
Yey I was taking about the "No output generated for simplyknockmainscript.psc, compilation failed."

**Comment by CineManiac93** [comment]
Same result.

![WindowsTerminal_HelJAubmKu](https://user-images.githubusercontent.com/49701521/197610950-ecee50af-f5a0-4045-92c7-cfc32d1cb94f.png)

**Comment by Michael-wigontherun** [comment]
Check to see if you have SkyUI's plugin and BSA loaded.
Delete the ChangedScripts folder and then let it decompile everything and let it process all of it.

If that still doesn't work you need to try to compile it using a compiler program from inside your Data folder. That should tell you a lot more about what is wrong.

**Comment by CineManiac93** [comment]
Will do, thank you for taking your time to help me.

**Comment by MoonbeamLure** [comment]
I just got home so let me try it and take a look at the output scripts and stuff

**Comment by MoonbeamLure** [comment]
Same error. Looks like it didn't pull off any of the digits necessary.

**Comment by Michael-wigontherun** [comment]
Show me

**Comment by MoonbeamLure** [comment]
<img width="1918" alt="image" src="https://user-images.githubusercontent.com/106170274/197622773-e5a551d8-af93-4309-9d6a-e9b63e99be5a.png">

The log showing the changes in FormID so it's a bit more clear what's happening hopefully: 

<img width="1316" alt="image" src="https://user-images.githubusercontent.com/106170274/197623072-6838c481-0706-425d-b2fa-f9c042a305b6.png">

According to the compacted mod files they are writing the correct compacted FormIDs, just for some reason it's not properly trimming the numbers on the left and in some cases it seems to actually be adding digits for whatever reason. 

I DID forget to correct the typo from the existing compacted mod data for my old folder of ESLify Everything which is the one I overwrote with the new build on accident lol so I just did that and am re-running it.

**Comment by Michael-wigontherun** [comment]
Did you update?

**Comment by MoonbeamLure** [comment]
Oh, you know what it is, I think it's only trimming right-to-left up to the first zero then adding the 6 digits. 

You see with the first formID, it goes 0xa042525, then it trims off the 42525, leaving 0xa0, then added on the 000824 -- 0xa042525 > 0xa0000824

You can see the same thing here with the other one: 0xa00aa13, trimmed to the first 0 is 0xa00, then add on the 6 digits is 0xa00000824.

**Comment by MoonbeamLure** [comment]
> Did you update?

I did, but I'll overwrite it again just in case I messed it up.

**Comment by Michael-wigontherun** [comment]
Its not the one that says latest, its a prerelease, it wont show up on the side bar you have to open releases then select the one with prerelease on it

or use this link [https://github.com/Michael-wigontherun/ESLifyEverything/releases/tag/V3.3.1](https://github.com/Michael-wigontherun/ESLifyEverything/releases/tag/V3.3.1)

**Comment by MoonbeamLure** [comment]
Yeah, looks like I must've downloaded the wrong one -- my bad. It did compile this time but I think the formIDs still might be wrong.I  don't know if Skyrim needs to have the preceeding numbers though, so it might be fine.

simplyknockmainscript.psc from changedscripts:
<img width="1169" alt="image" src="https://user-images.githubusercontent.com/106170274/197625538-dd881b73-b515-40fb-9e7c-515979b931a6.png">

_camp_InstinctsEffect.psc
<img width="1153" alt="image" src="https://user-images.githubusercontent.com/106170274/197625631-08c3250b-84e9-488c-b209-b74dd4af0526.png">

**Comment by Michael-wigontherun** [comment]
plug that 00813 into hex to dec it will be the same as if you used 813. and the same with 0824. I don't like loosing characters unless I have to.

**Comment by Michael-wigontherun** [comment]
I really don't know why his isn't working tho its weird.

**Comment by MoonbeamLure** [comment]
> I really don't know why his isn't working tho its weird.

From his log, looks like he's missing some sources for MCM Recorder. I advice he checks for JContainers / PapyrusUtil / SkyUI (sometimes SkyUI really hates compiling without the SDK sources too, not sure why) / UIExtensions.

**Comment by CineManiac93** [comment]
I will reinstall those, too

**Comment by Michael-wigontherun** [comment]
Yey but it should have no effect on simplyknockmainscript.psc as its not a MCM script.

**Comment by MoonbeamLure** [comment]
> Yey but it should have no effect on simplyknockmainscript.psc as its not a MCM script.

Yeah true. I do know that SkyUI is listed on simply knock's requirements, so I'm not sure how it's required. He might need the SDK to get SkyUI to cooperate..

**Comment by Michael-wigontherun** [comment]
@CineManiac93 make sure you have all of MCM Recorders requirements decompiled and loaded as well

**Comment by CineManiac93** [comment]
I did fresh installs of MCM Recorder and its requirements. Same result.

**Comment by MoonbeamLure** [comment]
> I did fresh installs of MCM Recorder and its requirements. Same result.

Can you provide a log of your ESLifyEverything output and your modlist please?

**Comment by CineManiac93** [comment]
How would you like the log since it exceeds pastebin's limit?

**Comment by MoonbeamLure** [comment]
Just the script compilation errors is fine!

**Comment by CineManiac93** [comment]
![chrome_0eICEuIH8g](https://user-images.githubusercontent.com/49701521/197640761-18a9a9e8-69ba-4193-bfbb-a6395db6ad77.jpg)
.......

https://pastebin.com/u4mDZ117

**Comment by MoonbeamLure** [comment]
> ![chrome_0eICEuIH8g](https://user-images.githubusercontent.com/49701521/197640761-18a9a9e8-69ba-4193-bfbb-a6395db6ad77.jpg) .......
> 
> https://pastebin.com/u4mDZ117

try https://pst.klgrth.io/ ? I think that site is supposed to be more friendly to code.

**Comment by CineManiac93** [comment]
Thank you!

https://pst.klgrth.io/paste/e5pxb

**Comment by MoonbeamLure** [comment]
Sorry, I wanted the modlist not load order -- if you're using MO2 you can find it in the profile folder under the modlist folder.

**Comment by CineManiac93** [comment]
Here's the AR MCMScript

https://pst.klgrth.io/paste/9v4wj

simplyknock

https://pst.klgrth.io/paste/hd5yq

**Comment by CineManiac93** [comment]
I use Vortex but MO should have the list as well

Modlist https://pst.klgrth.io/paste/8ynnq

**Comment by MoonbeamLure** [comment]
Everything looks ok, seems like. Can you verify that you can find .pex that starts with ski_ inside the ExtractedBSAModData\scripts folder?

**Comment by MoonbeamLure** [comment]
Also, can you see if you can share the whole ESLify Everything log now using the Spectre paste site

**Comment by CineManiac93** [comment]
Log lol
![chrome_k7OFbxWDIJ](https://user-images.githubusercontent.com/49701521/197643115-d3151657-c14e-43d4-b003-5f9758199f09.jpg)

ski_ in scripts

![explorer_XBWkHdIvmw](https://user-images.githubusercontent.com/49701521/197643349-e850946c-5a2d-450d-a8d0-3c97d1d196ec.jpg)

**Comment by MoonbeamLure** [comment]
Huh...and there wasn't any log lines that had compile errors? Without those errors it's hard for me to know what's going on. The only thing I can think of would be to download Papyrus Compilation App and try compiling the scripts from the ESLifyEverything\ChangedScripts folder by running the program through Vortex. If it works, just shove them into a folder that's super low in the mod order called "scripts" and then if it doesn't it'll give you some logs that should be helpful.

**Comment by CineManiac93** [comment]
Just the message at the end that I've posted before

**Comment by MoonbeamLure** [comment]
> Just the message at the end that I've posted before

Ok. Can you download and set up Papyrus Compilation App and then see if the scripts inside of the output\source\scripts or changedscripts folder compile?

**Comment by CineManiac93** [comment]
Downloading the app now

**Comment by CineManiac93** [comment]
from output/source/scripts

AR_MCMScript

https://pst.klgrth.io/paste/sgvqo

simplyknock

https://pst.klgrth.io/paste/w9a2j

**Comment by MoonbeamLure** [comment]
Oh, duh. That makes sense. From that log, all you'll need to do is:

1. Download Simply Knock and the SKSE64 DLL from here: https://www.nexusmods.com/skyrimspecialedition/mods/14098

2. Install SkyUI sources. This shouldn't be necessary for ESLify Everything necessarily, but since you're trying in PCA might as well: Download the source for SkyUI from here: https://github.com/schlangster/skyui, find the data folder inside the dist folder and install the stuff in there as if it's a mod. You should really only need the data/scripts/source folder. I kept the headers folder just in case, but I'm not sure if they're strictly necessary.

**Comment by CineManiac93** [comment]
Should SkyUI sources override conflicts with MCM Recorder?

**Comment by MoonbeamLure** [comment]
Go ahead and let the ones from MCM Recorder override them yeah. That should be fine. if they don't work, then you might need to have MCM Recorder's scripts be overwritten by SkyUI's.

**Comment by CineManiac93** [comment]
Then run ESLify again?

**Comment by MoonbeamLure** [comment]
As long as you compiled the scripts that had the changed formIDs you're good to go.

**Comment by MoonbeamLure** [comment]
You can try running ESLify Everything again if you'd like though, just to see if it works now that you have Simply Knock.

**Comment by CineManiac93** [comment]
Alright will run again to check

**Comment by CineManiac93** [comment]
![WindowsTerminal_cqzik2I3uA](https://user-images.githubusercontent.com/49701521/197655368-cd94ba2f-c4ab-4c01-8c69-7f2a74c4f084.jpg)

**Comment by CineManiac93** [comment]
I think I'm going to leave Immersive Interactions as an esp lol

**Comment by MoonbeamLure** [comment]
Fair enough lol. You should be good to go to manually compile the scripts as long as you make sure to compile the right ones. 

OnOptionMenuOpen is a SkyUI function for what it's worth. Might be something to look into there if you end up deciding to continue on.

**Comment by CineManiac93** [comment]
Alright, thank you so much for trying to help. We did get 1/2 to compile correctly, though.

**Comment by Michael-wigontherun** [comment]
@CineManiac93 if you didn't have Simply Knock then that script is unimportant to you. It will never run in game, its only added by Immersive Interactions to enable the animation when you knock on the door.

**Comment by CineManiac93** [comment]
Ok, sounds good. Thank you for all the help!
