### ISSUE TITLE
Aggregate Exception (Index was outside the bounds of the array).

### ISSUE THREAD

**Issue by Charolas** [Michael-wigontherun/ESLifyEverything#6]
[log .txt](https://github.com/Michael-wigontherun/ESLifyEverything/files/9905054/log.txt)

[ESLifyEverything_Log.txt](https://github.com/Michael-wigontherun/ESLifyEverything/files/9905078/ESLifyEverything_Log.txt)

**Comment by Michael-wigontherun** [comment]
What is inside of this file?
DAR file found at C:\Project Skyrim\Project Skyrim Special Edition\Data\Meshes\actors\character\animations\DynamicAnimationReplacer\_CustomConditions\2000000044\_conditions.txt

**Comment by Michael-wigontherun** [comment]
Is it nothing?

**Comment by Charolas** [comment]
It actually is nothing, weird, it should have a condition to random or death

**Comment by Michael-wigontherun** [comment]
Yey I didn't realize I left a debug line in the code now it's fixed in 3.5.3+
