### ISSUE TITLE
Not importing SKSE scripts (loose scripts?)

### ISSUE THREAD

**Issue by MoonbeamLure** [Michael-wigontherun/ESLifyEverything#7]
Hi again. I'm not sure if I'm doing anything wrong, but I was trying to ESL a mod that calls Schlongs of Skyrim's sos_api  scripts which itself uses SKSE sources. However, it seems like ESLify won't import the loose scripts it needs if the program doesn't directly need them? It feels like when I ESL other mods, it will import the loose scripts it needs to output to ESL but nothing else(? unsure on functionality). Normally, I can just drop whatever scripts are missing into the BSAModExtracted folder, but with the SKSE scripts they get overwritten by the Skyrim BSA versions of the scripts causing them to fail. 

For context, I have tried putting the SKSE scripts into the Data/scripts(/source) folder, and I have SKSE scripts installed as a separate mod as well. Both ways it ends up the same.

<img width="1894" alt="image" src="https://user-images.githubusercontent.com/106170274/199870686-65adb9e8-2350-43ca-8574-805869b430e3.png">

**Comment by Michael-wigontherun** [comment]
There loose scripts they should decompile like normal let it decompile the list across then check the source scripts in the extracted folder.

**Comment by MoonbeamLure** [comment]
> There loose scripts they should decompile like normal let it decompile the list across then check the source scripts in the extracted folder.

Ok. I double-checked:

Here's utility.psc as from ExtractedBSAModData\Source\Scripts: https://pastebin.com/gEda6LJk It's the non-SKSE version. so, it's like either it's not being copied over or it just doesn't overwrite or something.

And, for the schlongs of skyrim scripts none of the scripts with sos_* are in there.  

I also went through some of the other mods and noticed that some mods have some scripts they're importing but not others. I honestly have no idea why. I just assumed it wasn't supposed to import every loose script, but it sounds like it's supposed to.

**Comment by Michael-wigontherun** [comment]
It decompiles mine fine, are they active as active inside MO2 and or are they overwritten by something else.

**Comment by MoonbeamLure** [comment]
> It decompiles mine fine, are they active as active inside MO2 and or are they overwritten by something else.

Ok. Yeah, the mods are active inside MO2 and they're not overwritten by something else either.

**Comment by Michael-wigontherun** [comment]
Are you letting it decompile?

**Comment by MoonbeamLure** [comment]
I don't press anything at all while it's working.

Normally, it will do the BSA'd mods and decompile those scripts which tends to take a little bit, then that terminal window closes, ESLify Everything notifies me that it's decompiling loose scripts another terminal window pops up.  Then, normally it will either immediately close with having nothing written into the window or it will only show decompiling of ~80-100 scripts and then close the window and proceed with the next steps. It has been doing that to me really since I obtained the program but it sounded like it was intended based on how I interpreted what you said to me in the past, so I didn't think too much of it until this.

**Comment by Michael-wigontherun** [comment]
That doesn't help or make sense the only reason it should only be decompiling 80-100 is your clicking something and closing it before it finishes

**Comment by Michael-wigontherun** [comment]
Unless you really only have that many loose scripts which I feel even SKSE has more then that.

**Comment by MoonbeamLure** [comment]
I can promise I'm not clicking anything. The BSA window goes through just fine, then the loose script one comes up and closes like I said. If I were pressing buttons, wouldn't it be likely that I was closing it sometimes on the BSA window and sometimes on the loose script window? But in my case it's _only_ on the BSA window

Out of curiosity I searched for .pex in windows explorer shows that I have at the moment ~15k loose scripts. 

I also just ran it to double check and the BSA window ran just fine, and the loose script window popped and nothing was written. It was just the cursor and an empty window then it closed like 5-10 seconds later moving onto the next step.

**Comment by MoonbeamLure** [comment]
err...sorry. only on the _loose scripts_ window. Mistype.

**Comment by Michael-wigontherun** [comment]
Are you on a outdated version?

**Comment by Michael-wigontherun** [comment]
Download this enable devlog then tell me where the script folder is pointing to below the checking decompiling ____ scripts

**Comment by MoonbeamLure** [comment]
> Download this enable devlog then tell me where the script folder is pointing to below the checking decompiling ____ scripts

Nah, not out of date. I also delete the whole folder and re-set it up in case overwriting was breaking it. 

And okay. I ended up falling asleep and now I gotta go to work but it's a short day so I'll be able to check in a few hours.

**Comment by MoonbeamLure** [comment]
Alright, I'm available. I don't see any devappsettings file I can download that looks different than the one bundled inside of the program though.

**Comment by Michael-wigontherun** [comment]
its the save file as previous, i fogot to bundle it again

**Comment by MoonbeamLure** [comment]
So I just ran it, it does see all the BSAs and increments properly through the BSAs resolving to scripts\script.pex I'm assuming in the BSAModExtracted folder or whatever it's called.

Then, it runs champollion for BSA scripts, which it took a few minutes and opened up a new terminal window for Champollion to run with. Once that was done, it wrote "running Champollion on loose scripts", opened up another terminal where it just sat there for  a few seconds, didn't see anything seemingly and then closed. There was nothing telling me what directory it would be running. I did look over the source code and I double checked that my paths should be leading to the correct places and it does seem so.  See below.

<img width="411" alt="image" src="https://user-images.githubusercontent.com/106170274/200071662-a6f4d211-3ef5-4b06-a7a5-e8160ee5e9c7.png">

<img width="872" alt="image" src="https://user-images.githubusercontent.com/106170274/200072055-ee2c1b1f-d11a-4e51-b7b6-220968f527eb.png">

My ESLify Everything folder goes into C:\Modding\Tools\SSEEdit 4.0.4\ESLify Everything. Could that be the issue?

**Comment by Michael-wigontherun** [comment]
I didn't link the prerelease either [https://github.com/Michael-wigontherun/ESLifyEverything/releases/tag/V3.8.1P](https://github.com/Michael-wigontherun/ESLifyEverything/releases/tag/V3.8.1P) I wanted you to show me what was under the Running Champollion lines.

I don't know what you mean by 
> My ESLify Everything folder goes into C:\Modding\Tools\SSEEdit 4.0.4\ESLify Everything. Could that be the issue?
>
If thats where its installed then it should be fine

**Comment by MoonbeamLure** [comment]
> I didn't link the prerelease either https://github.com/Michael-wigontherun/ESLifyEverything/releases/tag/V3.8.1P I wanted you to show me what was under the Running Champollion lines.
> 
> I don't know what you mean by
> 
> > My ESLify Everything folder goes into C:\Modding\Tools\SSEEdit 4.0.4\ESLify Everything. Could that be the issue?
> 
> If thats where its installed then it should be fine

Yeah that's what I meant. Ok.

Also, yeah there was no paths at all under that. Running on the new one now though

**Comment by Michael-wigontherun** [comment]
Then you either didn't download the prerelease or you didn't enable devlogging

**Comment by MoonbeamLure** [comment]
Yeah yeah I was on the old version when I checked before -- I downloaded the pre-release and am running it with devlogging enabled right now! I saw a path for the BSA scripts which it's decompiling right now so I will update you in a sec.

**Comment by MoonbeamLure** [comment]
Ok, so the file path inside ESLify Everything was correct
<img width="695" alt="image" src="https://user-images.githubusercontent.com/106170274/200076379-2d3000ae-0fcb-4076-8df1-f6f7938e1b25.png">

But I saw something weird inside of Champollion during loose scripts that didn't look like it normally does, like it showed some text instead of a terminal but it moved too fast for me to snipping tool so I ran it a second time to see if it would show it again and it didn't -_- so I don't know.  But I am going to run it one more time after deleting the output scripts just in case...

**Comment by MoonbeamLure** [comment]
Yep, nothing -_- the log for outputting loose scripts stayed empty again. it didn't properly import any of the SKSE or really most of my other loose scripts at all. so annoying that I missed the message. For the time it did show something in the log, I think I made out the word "Skyrim" (not Skyrim Special Edition) fwiw, I believe as the last path. I do know my MO2 profile/install is C:\Modding\Skyrim. Wonder if Champollion itself is looking in the MO2 folder instead of the proper SSE\Scripts folder even though ESLify Everything output the right path?

**Comment by Michael-wigontherun** [comment]
That snippet is the file path Champollion is using

**Comment by MoonbeamLure** [comment]
I'm running it from within MO2 too. :/ I'm really confused lol. it's so weird because I have the SKSE scripts as its own mod from within MO2 and then I have them also in the data/scripts folder just in case as well and they aren't getting imported either way, even though the path on ESLify looks correct...

**Comment by Michael-wigontherun** [comment]
I updated the prerelease to now include logging for the Champollion logging, it wont open a second window just see the ESLifyEverything_Log.txt and see what that says at the end.

It should look something like this. near the end show me just the last couple of those including the last where it says how many "____ files were processed ______"
> C:\Modding\SkyrimSE\ESLifyEverything\ESLifyEverything\bin\Debug\net6.0\Data\Scripts\_DE_TentDoorFurScript.pex decompiled to C:\Modding\SkyrimSE\ESLifyEverything\ESLifyEverything\bin\Debug\net6.0\ExtractedBSAModData\Source\Scripts\_DE_TentDoorFurScript.psc
C:\Modding\SkyrimSE\ESLifyEverything\ESLifyEverything\bin\Debug\net6.0\Data\Scripts\_DE_TentDoorScript.pex decompiled to C:\Modding\SkyrimSE\ESLifyEverything\ESLifyEverything\bin\Debug\net6.0\ExtractedBSAModData\Source\Scripts\_DE_TentDoorScript.psc
C:\Modding\SkyrimSE\ESLifyEverything\ESLifyEverything\bin\Debug\net6.0\Data\Scripts\_DE_TentExtScript.pex decompiled to C:\Modding\SkyrimSE\ESLifyEverything\ESLifyEverything\bin\Debug\net6.0\ExtractedBSAModData\Source\Scripts\_DE_TentExtScript.psc
C:\Modding\SkyrimSE\ESLifyEverything\ESLifyEverything\bin\Debug\net6.0\Data\Scripts\_DE_TentItemFurScript.pex decompiled to C:\Modding\SkyrimSE\ESLifyEverything\ESLifyEverything\bin\Debug\net6.0\ExtractedBSAModData\Source\Scripts\_DE_TentItemFurScript.psc
C:\Modding\SkyrimSE\ESLifyEverything\ESLifyEverything\bin\Debug\net6.0\Data\Scripts\_DE_TentItemScript.pex decompiled to C:\Modding\SkyrimSE\ESLifyEverything\ESLifyEverything\bin\Debug\net6.0\ExtractedBSAModData\Source\Scripts\_DE_TentItemScript.psc
31 files processed in 0.0257919 s
Source code Champollion Ended.
>

**Comment by Michael-wigontherun** [comment]
[https://github.com/Michael-wigontherun/ESLifyEverything/releases/tag/V3.8.1P](https://github.com/Michael-wigontherun/ESLifyEverything/releases/tag/V3.8.1P)

**Comment by MoonbeamLure** [comment]
Ok this is weird. It shows the BSA Champollion as processing 20k files in 6 seconds: 
<img width="315" alt="image" src="https://user-images.githubusercontent.com/106170274/200082512-2f0d995c-3560-4b1d-ac88-dcba123b90c7.png">

Then, it started loose scripts champollion, ran through ~60 files (from line 28052 to 28119 and then just stopped with a cut off output directory without telling me how many files were processed and in how long: 
<img width="1646" alt="image" src="https://user-images.githubusercontent.com/106170274/200082785-62013c8a-8fb9-4998-af24-2f41a18ccd2a.png">

**Comment by Michael-wigontherun** [comment]
Something must be overwriting the SKSE scripts then

Do you have this enabled?
![image](https://user-images.githubusercontent.com/43317302/200083258-0431aea9-e468-4919-9c76-fae0bc63b7d4.png)

**Comment by Michael-wigontherun** [comment]
And do you hit yes for any reason?

**Comment by MoonbeamLure** [comment]
I have it set to false, and I only hit yes when it's a BSA that needs to be extracted so I can delete a dummy plugin OR it's an oldrim mod that I'm porting over to SSE (the big example is the ESF companion mod that's used in DarkLadyLexy's guide). In this particular installation, the only mods I have done so were the ones I was instructed to as per her guide.

**Comment by MoonbeamLure** [comment]
I don't understand, how could something be overwriting my SKSE scripts when the source code champollion crashes after ~60 scripts with an underscore character start? Seems like it's going alphabetically, so it wouldn't have even a chance to output any SKSE scripts?

**Comment by Michael-wigontherun** [comment]
I don't understand it says that Champollion processed 20600 files under the loose Champollion run

**Comment by Michael-wigontherun** [comment]
I don't understand show me the last few lines in the Log
under 
"Running Champollion on loose scripts."
and above 
"Source code Champollion Ended."

**Comment by MoonbeamLure** [comment]
I ran it again after deleting the SKSE scripts inside of my folder (data\scripts), just in case that was a problem: 

<img width="540" alt="image" src="https://user-images.githubusercontent.com/106170274/200084179-2baecd65-a3d1-419a-96c1-6def2042e258.png">

This time instead of trying to import any loose scripts at all, it just like...didn't lol. 



> I don't understand it says that Champollion processed 20600 files under the loose Champollion run

It doesn't, the picture says 20,600 files processed in 6.39~ seconds and then BSA scripts champololion ended. Then it started running on loose scripts and ran through the first ~60, then it ran into that half-printed directory and just stopped running and this time it didn't even try to import loose scripts.

**Comment by Michael-wigontherun** [comment]
in the txt file not the console

**Comment by MoonbeamLure** [comment]
that IS the text file

**Comment by MoonbeamLure** [comment]
here's a bigger snippet. you can see that the log is getting scripts printed into it for the BSA extracted section but not for the loose scripts. also included the first line of the lines where it shows the scripts being changed
<img width="1643" alt="image" src="https://user-images.githubusercontent.com/106170274/200084524-44882325-351e-4fbb-a7bf-35db862a564c.png">

**Comment by Michael-wigontherun** [comment]
Huh ok your notepad is in Darkmode it looks like the CMD. Are you letting it run all the way through the compiler?

**Comment by Michael-wigontherun** [comment]
Hmmmmmm it should be doing something at least

**Comment by Michael-wigontherun** [comment]
umm is your firewall flagging Champollion and saying you can't start or something?

**Comment by MoonbeamLure** [comment]
Yep, and it errors out a bunch. From the CMD log, since ESLify Everything's log doesn't show script errors: 
<img width="850" alt="image" src="https://user-images.githubusercontent.com/106170274/200084705-3ccd380d-30ab-4db0-8c82-5949861ce81e.png">

there's a bunch more that all point to SKSE functions and other loose scripts that should be being imported.

What's even weirder is that it tried to import some files the first time, like I said and it tried to run through like ~60 files https://user-images.githubusercontent.com/106170274/200082785-62013c8a-8fb9-4998-af24-2f41a18ccd2a.png

then there was one file where it only printed half of the directory and then right after it just ended the source code champollion. There's like 15k loose scripts in my data directory, so...



> umm is your firewall flagging Champollion and saying you can't start or something?

I thought it might be, but I tried it with disabling the active virus protection thing like you have to do with FNIS, I also have all of my Skyrim SE and MO2 folders set to not be blocked etc. in the windows settings, so I don't think that's it. Plus, if it were then you'd think it'd fail on the BSA scripts and not the loose scripts right?

**Comment by MoonbeamLure** [comment]
Do you think I should go grab all the libraries I'd need to compile ESLify Everything and try to debug it with breakpoints?

**Comment by Michael-wigontherun** [comment]
Something is happening inside of Champollion that shouldn't be happening I can't really debug stuff that internally happens inside of Champollion. All this is doing is running the Champollion.exe with command line arguments. The thing that doesn't make sense and is the fact that the BSA execution is working perfectly fine while the loose run is just not.

If you want to download the project and tinker with that to see if you can find something out then go ahead as long as you don't try to upload anything.

**Comment by MoonbeamLure** [comment]
My thought is that it's trying to 

> Something is happening inside of Champollion that shouldn't be happening I can't really debug stuff that internally happens inside of Champollion. All this is doing is running the Champollion.exe with command line arguments. The thing that doesn't make sense and is the fact that the BSA execution is working perfectly fine while the loose run is just not.
> 
> If you want to download the project and tinker with that to see if you can find something out then go ahead as long as you don't try to upload anything.

Okay, thanks. And yeah, definitely won't upload anything.

**Comment by Morribyte** [comment]
So...I think I found something wrong with champollion. So, I added a cmd exe to MO2 and ran the command as written in eslify everything, check this out: 

<img width="1430" alt="image" src="https://user-images.githubusercontent.com/106170274/200089171-d8c507ae-5a4f-4a0d-87b3-478f1b4d1bad.png">

If I run Champollion with the -t flag, after 2 or 3 scripts it just breaks after a few lines. 
<img width="1449" alt="image" src="https://user-images.githubusercontent.com/106170274/200089344-a463ed08-a760-4f74-861d-6c1b8262bfab.png">

I have no idea why it would do it with this. If I run it without the -t flag, everything runs through as expected. 

What's even weirder,  is if I run Champollion through the same directory, but telling it to take scripts from ExtractedBSAModData\scripts and put the decompiled scripts into ExtractedBSAModData\source\scripts, it works.

So...yeah. I'm guessing that Champollion is breaking because of the -t command when I'm trying to copy from MO2's vfs. Can you take off the -t flag from the loosechamp argument but keep it for the BSA argument?

**Comment by Morribyte** [comment]
<img width="1609" alt="image" src="https://user-images.githubusercontent.com/106170274/200089594-1997938e-12db-47f3-97ab-aa6cbb2f7d2e.png">

Forgot the other picture lol

**Comment by Morribyte** [comment]
Hrm...seems like champollion freezes even without the -t command. It's stopping at the letter S in my loose scripts even though I have scripts up to z. 

right now, i am testing to see if using command prompt to execute a move command into a folder in ESLifyEverything called "loose scripts" freezes, and if not then running champollion on that into the source/scripts folder.

**Comment by Morribyte** [comment]
Hmm, so actually I think it might just be a single mod I've installed...? Either way, I'm going to stop updating this until I can find a concrete issue.

**Comment by MoonbeamLure** [comment]
I found the issue. One of the mods I have apparently has corrupted scripts or something lol, if I de-activate that mod it will actually process the scripts properly. And if I decompile the scripts manually it just gives me a 0 KB file.

**Comment by Michael-wigontherun** [comment]
All right that's good to know
