### ISSUE TITLE
Compiler portion freezes?

### ISSUE THREAD

**Issue by MoonbeamLure** [Michael-wigontherun/ESLifyEverything#9]
Hi there. I've noticed a bug that seems to happen to me now with the compiling portion of ESLify Everything. It will just get stuck on displaying the "Important <" line, as it normally does while it's working. I left it on all night last night because I just assumed that the program needed more time, but this morning I woke up and the command log still hadn't progressed into the sub-plugin compaction stage.

I don't see any logs that illuminate anything, dev logging or not. It just shows the Important < line and then nothing.

I've noticed that it DOES output at least some scripts. So, it's not like it's broken completely. Especially when there's a small number of changed scripts it's not much of a big deal. 

But when there's a lot of scripts, it will output some scripts and print if it's errored out for a few of them. It will then just stop working and the number of scripts inside the folder won't increase. And sometimes, I have no idea newly compiled scripts will start appearing in the folder once the program is closed, but it will never be all of them. 

I don't think it's the compiler on my end, because it works just fine when I use PCA to compile the scripts manually.

**Comment by Michael-wigontherun** [comment]
There is nothing I can do if its on the Compiler. There is nothing I can do to fix it and no way to detect whether a program is not working. The only way to get out of it is to end the compiler task in Task Manager that will allow ESLify Everything to continue and it will output what scripts didn't compile, based off what is in the ChangedScripts folder and the Output folder.

**Comment by MoonbeamLure** [comment]
Ok, so to confirm that means that the compiler doesn't crash for you and ESLify Everything will successfully go into the sub-compaction step? 

If so, that actually helps me a lot because that means that there's an issue on my end I can address. Thanks.

**Comment by MoonbeamLure** [comment]
Yeah I was able to find my papyrus compiler command window and close it and ESLify Everything successfully finished. No idea why my papyrus compiler would freeze. Time to do some investigations. Thanks.

**Comment by Michael-wigontherun** [comment]
I can add a failsafe to send it into compile one by one mode, I have been debating with myself whether it would be worth it.

**Comment by MoonbeamLure** [comment]
If that doesn't take too much effort I think that's something I'd appreciate seeing added, yeah.

**Comment by Michael-wigontherun** [comment]
I'll push it in a few days. I am preoccupied with another project that I feel is important to my modding sanity.
